---
title: bug
createTime: 2024-04-22 22:03:04
permalink: /pages/24c16b/
categories:
  - 语言
  - python
tags:
  - 
---
## 记录一个自己的愚蠢

今天写 python, 遇到就个问题是程序可以在自己的文件内运行, 但是别的文件调用就失败。

最后发现是因为 asyncio 我在 if __name__ == "__main__ " 中引用了，但别的函数调用是时候就没有，想到这么个 bug 浪费我俩小时，深感自己技术不行。
